import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from 'next/headers';
import LogoutButton from "./components/logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const cookieStore = await cookies();

  const authCookie = cookieStore.get('auth')?.value;
  const user = authCookie ? JSON.parse(authCookie) : null;
  const auth = authCookie;
  const userRol = user ? user.rol : "Usuario";

  return (
    <html lang="es">
      <body className="bg-white">
        <header className="bg-white shadow">
          <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold text-gray-900">Mi Aplicación</h1>

            <nav className="space-x-4">
              {userRol != "ADMIN" ? (
                <Link href="/usuario" className="text-gray-700 hover:text-indigo-600 transition">
                  Inicio
                </Link>
              ) : (
                <Link href="/admin" className="text-gray-700 hover:text-indigo-600 transition">
                  Inicio
                </Link>
              )}
              

              {auth ? (
                <LogoutButton /> 
              ) : (
                <Link href="/" className="text-gray-700 hover:text-indigo-600 transition">
                  Iniciar Sesión
                </Link>
              )}
            </nav>
          </div>
        </header>
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}